### ISSUE TITLE
Document payload expectations for POST:/sql

### ISSUE THREAD

**Issue by rflprr** [datadotworld/dwapi-spec#16]
Current documentation doesn't specify that `query` is required to be passed in the POST request for SQL queries.

**Comment by lukewhyte** [comment]
Does this issue refer to the POST:/sql docs [here](https://apidocs.data.world/v0/sql/sql-query)? If so, I've noticed that it also isn't possible to add the query param under the "Try it out" tab, which is a bit confusing.

**Comment by rflprr** [comment]
@lukewhyte  Thanks for asking. https://github.com/datadotworld/dwapi-spec/issues/73 should improve things significantly.
